# Generated by Django 5.2.4 on 2025-08-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(choices=[('Products List', 'Products List'), ('Marketing List', 'Marketing List'), ('Order List', 'Order List'), ('Media Plans', 'Media Plans'), ('Offer Pricing SKUs', 'Offer Pricing Skus'), ('Clients', 'Clients'), ('Suppliers', 'Suppliers'), ('Customer Support ', 'Customer Support'), ('Sales Reports', 'Sales Reports'), ('Finance & Accounting', 'Finance And Accounting'), ('NoNamePage', 'Default')], default='NoNamePage', max_length=50),
        ),
    ]
